infinyon/fluvio-client-python

.github/workflows/cloud.yml
README.md
tests/test_fluvio_python.py

This cleans up the topic names for the python client so that the unit tests can be used with all PRs.

Updated unit tests to be uuids

---

.github/workflows/publish.yml
setup.py

It looks like the sdist job is not building a .tar.gz file, I think that this should fix that

ci: fix sdist upload

---

Cargo.lock
Cargo.toml
macos-ci-tests/test_connect.py
setup.py
src/glue.rs.in
src/lib.rs

Most of this is actually a refactor to make rust-analyzer work nicely with this codebase. The actual changes were on the imports and adding `fluvio-spu-schema` as a dependency.

Update to fluvio 0.14

---

.github/workflows/ci.yml
.github/workflows/cloud.yml
.github/workflows/publish.yml
requirements.txt

Closes #197.
Supersedes #190, #189, #187.
This is slowing development of #180 so let's just remove python 3.7 support.

Updated flake8, pycodestyle, pyflacks, remove python 3.7 support

---

fluvio/__init__.py
integration-tests/test_fluvio_python.py
src/glue.rs.in
src/lib.rs

This PR adds the `Fluvio::connect_with_config` method. It also adds `FluvioConfig` structure to be used along with the added method.
closes https://github.com/infinyon/fluvio-client-python/issues/287

feat: Implement `Fluvio::connect_with_config`, add `FluvioConfig`

---

.github/workflows/publish.yml

chore: update cibuildwheel

---

.github/workflows/cloud.yml

`fluvio cloud 0.2.17` is multi cluster so it does not default to creating a cluster profile 
Add a sync command to create a profile in ci

chore: fluvio-cloud-ci fix profile cfg

---

src/lib.rs

This PR wraps most `run_block_on` calls in a `py.allow_threads` function, releasing the Python GIL for the duration of the `run_block_on` call. This is especially important for `PartitionConsumerStream.next` which might block indefinitely.
The issue arose with me, when running a `PartitionConsumer` in a separate thread and using the `stream` method. The underlying call to `PartitionConsumerStream.next` was waiting for incoming messages while holding the Python GIL, effectively prohibiting the main thread to do any work.
I think that releasing the GIL is mostly important for the `PartitionConsumerStream.next` method, because it may block indefinitely (if no messages arrive), but I wrapped all other `run_block_on` calls as well, while I was at it.
I left out the instances of `run_block_on` …

feat: release GIL for most "run_block_on" calls

---

fluvio/__init__.py

For both the `Fluvio.multi_partition_consumer` and `Fluvio.multi_topic_partition_consumer` methods, the PyO3-types were wrapped in a `PartitionConsumer` instead of a `MultiplePartitionConsumer` type.
This PR fixes this inconsistency.

fix: wrap multiple-partition-consumer correctly

---

fluvio/__init__.py
integration-tests/test_fluvio_python.py
src/lib.rs

This is a WIP pull request addressing issue #389.
It adds two python representations `ProduceOutput` and `RecordMetadata` allowing to retrieve metadata for records sent by the `TopicProducer`. The implementation tries to mimic the existing rust interface. However, the PyO3-wrapper `ProduceOutput` places the inner (native) `ProduceOutput`into a `Cell` because its only method `main`consumes `self`, which can not be realized with a PyO3-wrapper.
This means that a subsequent call to the `wait` method will find a `Default`version of the object and result in a `ProduceError::GetRecordMetadata(None)` (in pure Rust, such a subsequent call is impossible as the underlying `ProduceOutput` would not exist anymore after the first call).
I would like to hear your suggestions regarding this realization …

feat: add python realization of ProduceOutput and RecordMetadata

---

Makefile

Change from deprecated "python setup.py develop" to "pip install -e ."
This removes annoying deprecated setup.py message (for which direct
calling is deprecated not setup.py itself?)
https://github.com/pypa/setuptools/issues/917#issuecomment-1759240469

fix: change to recommended dev build

---

Makefile

This reverts commit 83b4fc005563b2b2dc1c8a37a6ca7c0da3601e54.
The reverted commit and https://github.com/infinyon/fluvio-client-python/pull/393
seem to be incompatible, reverting this for now.

Revert "fix: change to recommended dev build (#396)"

---

.github/workflows/latest-dev-fluvio.yaml
Cargo.toml
integration-tests/smartmodule-filter-on-a/Cargo.toml
integration-tests/test_fluvio_python.py
src/lib.rs

- **chore: ci, change latest fluvio workflow to python 3.12**
- **chore: Cargo.toml sort deps**
- **chore: update fluvio deps**
- ** update to fluvio 0.11.11 **
- **fix: flvuio client code updates for 0.11.11 **

chore: fluvio update to 0.11.11

---

.github/workflows/ci.yml
.github/workflows/cloud.yml
.github/workflows/latest-dev-fluvio.yaml
fluvio/__init__.py
integration-tests/test_fluvio_python.py
setup.py

this also may fix some test failures due
to improved concurrency in the fluvio python client

chore: use admin module instead of cli in tests

---

.github/workflows/ci.yml
.github/workflows/publish.yml
Cargo.toml
cross/Dockerfile.aarch64-unknown-linux-gnu
cross/Dockerfile.arm-unknown-linux-gnueabihf
cross/Dockerfile.armv7-unknown-linux-gnueabihf

Fixing the following cross compilation problem:
```
warning: aws-lc-sys@0.20.1: CMAKE environment variable set: cmake
warning: aws-lc-sys@0.20.1: Generating bindings - external bindgen. Platform: armv7-unknown-linux-gnueabihf
error: failed to run custom build command for `aws-lc-sys v0.20.1`
Caused by:
process didn't exit successfully: `/target/release/build/aws-lc-sys-857292f24e7ab0b5/build-script-main` (exit status: 101)
--- stdout
cargo:rerun-if-env-changed=AWS_LC_SYS_NO_PREFIX
cargo:rerun-if-env-changed=AWS_LC_SYS_INTERNAL_BINDGEN
cargo:rerun-if-env-changed=AWS_LC_SYS_EXTERNAL_BINDGEN
cargo:rerun-if-env-changed=AWS_LC_SYS_NO_ASM
cargo:rerun-if-env-changed=AWS_LC_SYS_CMAKE_BUILDER
cargo:rerun-if-env-changed=AWS_LC_SYS_STATIC
cargo:rerun-if-env-changed=CMAKE …
```

fix: bindgen dependency when cross compilation

---

.github/workflows/ci.yml
.github/workflows/publish.yml
tools/cibw_before_all_linux.sh

use new images to build wheels because the old one it was not identifying clang.

fix: publish build wheels

---

.github/workflows/ci.yml
.github/workflows/publish.yml
Makefile
fluvio/__init__.py
fluvio/new_topic.py
fluvio/specs.py
fluvio/topic.py
fluvio/utils.py
integration-tests/test_fluvio_python.py
requirements.txt
setup.py
src/lib.rs
tests/test_new_topic.py
tests/test_topic.py
tests/test_utils.py

Simple (1 partition and 1 replica):
```python
fluvio_admin = FluvioAdmin.connect()
fluvio_admin.create_topic("topic_name")
```
or
```python
fluvio_admin = FluvioAdmin.connect()
topic_spec = TopicSpec.new()
fluvio_admin.create_topic("topic_name", topic_spec)
```
Advanced:
```python
fluvio_admin = FluvioAdmin.connect()
topic_spec = (
TopicSpec.create()
.with_partitions(3)
.with_replications(3)
.with_max_partition_size("1Gb")
.with_retention_time(3600)
.with_segment_size("10M")
.as_system_topic()
.build()
)
fluvio_admin.create_topic("topic_name", topic_spec)
```
~I am using `NewTopic` only because [kafka-python](https://github.com/dpkp/kafka-python) also uses a class called `NewTopic`~

feat: improve topic creation api

---

Cargo.toml
fluvio/__init__.py
integration-tests/test_base.py
integration-tests/test_consume.py
src/lib.rs

Should solve: https://github.com/infinyon/fluvio-client-python/issues/514
Needs: 
new API:
```python
import fluvio
fluvio = Fluvio.connect()
topic = "a_topic"
builder = ConsumerConfigExtBuilder(topic)
builder.offset_start(Offset.beginning())
builder.offset_strategy(OffsetManagementStrategy.MANUAL)
builder.offset_consumer("a-consumer")
config = builder.build()
stream = fluvio.consumer_with_config(config)
num_items = 2
records = [bytearray(next(stream).value()).decode() for _ in range(num_items)]
stream.offset_commit()
stream.offset_flush()
```
Also added consumer API (needed for integration tests)

feat: add offset management integration to consumer stream

---

.github/workflows/ci.yml
.github/workflows/cloud.yml
.github/workflows/latest-dev-fluvio.yaml
.github/workflows/publish.yml
Cargo.toml
Makefile
integration-tests/test_fluvio_python.py
integration-tests/test_signals.py
integration-tests/test_signals_async.py
setup.py
src/lib.rs
src/produce_output.rs

feat: add graceful shutdown

---

.github/workflows/cloud.yml
integration-tests/test_consume.py
integration-tests/test_signals.py
integration-tests/test_signals_async.py

The ci for cloud uses the same cluster.
This changes make the test pass even one consumer it was not deleted right.
Probably because it: https://github.com/infinyon/fluvio/issues/4308
Or a shutdown without handling teardown.

test: fix cloud tests using old consumers
