infinyon/fluvio-client-python

- .github/workflows/ci.yml
- .github/workflows/publish.yml
- .gitignore
- Cargo.toml
- Makefile
- setup.py
Random cleanups and initial stuff for pypi publishing steps to CI.
> Initial publish ci workflow

- .github/workflows/ci.yml
- .github/workflows/publish.yml
- .gitignore
- Cargo.lock
- Cargo.toml
- MANIFEST.in
- Makefile
- README.md
- build.rs
- fluvio/__init__.py
- setup.py
> Cleanups readme and distribution fixes

- .github/workflows/ci.yml
- .github/workflows/docs.yml
- .gitignore
- Makefile
- README.md
- setup.py
> Initial attempt at docs ci

- Cargo.lock
- Cargo.toml
- README.md
This should have happened in the last PR but oh well.
> Updated to fluvio from crates.io

- .github/workflows/ci.yml
- README.md
- fluvio/__init__.py
- setup.py
- src/glue.rs.in
- tests/test_fluvio_python.py
Somehow, I forgot to actually make use of `Offset`. This fixes it.
> Added offset support

- .gitignore
- Cargo.lock
- Cargo.toml
- Makefile
- fluvio/__init__.py
- setup.py
- src/glue.rs.in
- tests/test_fluvio_python.py
Initial stuff for batch produce to show difficulty. Depends on infinyon/fluvio#896, subtask of infinyon/fluvio#847.
> Batch produce

- requirements.txt
> Dependabot updates

- Cargo.lock
- Cargo.toml
- Makefile
- macos-ci-tests/test_connect.py
- setup.py
> Updates to fluvio 0.9.5

- .github/workflows/publish.yml
- Cargo.lock
- Cargo.toml
- cross/Dockerfile.arm-unknown-linux-gnueabihf
- cross/Dockerfile.armv7-unknown-linux-gnueabihf
- requirements.txt
- setup.py
- src/glue.rs.in
> Bump stuff to fluvio 0.12

- README.md
send_string() NOT send_record()
> Fix README producer example

- .github/workflows/ci.yml
- .github/workflows/publish.yml
- Cargo.lock
- Cross.toml
- Makefile
- cross/Dockerfile.aarch64-unknown-linux-gnu
- cross/Dockerfile.arm-unknown-linux-gnueabihf
- integration-tests/test_fluvio_python.py
- setup.py
- tools/aarch64-linux-gnu-zig-c++
- tools/aarch64-linux-gnu-zig-cc
- tools/cibw_before_all_linux.sh
> Refactor some publish CI and add aarch64-manylinux to release

- Makefile
- fluvio/__init__.py
- integration-tests/test_fluvio_python.py
- setup.py
> Change iterator to be generator for consumer streams

- fluvio/cloud.py
- setup.py
- src/cloud/error.rs
- src/cloud/mod.rs
- src/glue.rs.in
- src/lib.rs
> Fix cloud login in jupyter notebook

- fluvio/__init__.py
closes https://github.com/infinyon/fluvio-client-python/issues/285
Removed the part about generating and using default config.
> doc: fix doc of Fluvio::connect

- setup.py
Want to make new release with `Fluvio::connect_with_config` and `FluvioConfig`
> bump: bump version to prepare for release

- Cargo.toml
- src/lib.rs
fixes https://github.com/infinyon/fluvio-client-python/pull/334 and https://github.com/infinyon/fluvio-client-python/pull/363
> build(deps): Bump tokio and rpassword

- .github/workflows/publish.yml
- tools/cibw_before_all_linux.sh
fixes https://github.com/infinyon/fluvio-client-python/issues/366
Fixed missing perl dependency and new upload-artifact@v4 behavior.
> fix CI publish workflow

- .github/workflows/publish.yml
- chore: ci eplace outdated rust toolchain action
- chore: ci, fix pypi publish d/l
> chore: ci fix d/l artifacts

- Cargo.toml
- setup.py
- src/cloud/mod.rs
- src/error.rs
- src/lib.rs
- **fix: cargo clippy**
- **chore: update to fluvio 0.11.5**
> chore: update to fluvio 0.11.5

- src/lib.rs
@digikata Please check it, it fix the clippy issues.
> Clippy fix.

- Cargo.toml
- fluvio/__init__.py
- integration-tests/test_fluvio_python.py
- src/lib.rs
trigger CI on branch
After fluvio 0.11.5 is released, the Cargo references can be changed to that
> Shylock: feature/async

- .github/workflows/publish.yml
> chore: ci, push docs on tag event

- .github/workflows/cloud.yml
fix interaction between cache and rust update
> chore: ci cloud fix

- .github/workflows/ci.yml
- .github/workflows/cloud.yml
- CHANGELOG.md
- Cargo.toml
- README.md
- fluvio/__init__.py
- integration-tests/test_fluvio_python.py
- integration-tests/test_produce.py
- requirements.txt
- setup.py
- src/lib.rs
- src/produce_output.rs
- **chore: python 3.8 EOL**
- **chore: update CHANGELOG.md**
- **chore: README.md update**
- **fix: produce output result misconversion always resulted in None**
> fix: producer async_wait error return

- Cargo.toml
- src/produce_output.rs
> chore: bump fluvio to 0.12.1 and rev crate version

- CHANGELOG.md
> chore: release 0.17.0
